name: caller

on:
  push:
    branches:
    - 'dev'
  pull_request:
    branches:
    - 'dev'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: bakuppus/github-action-reusable-workflow/.github/workflows/reuseable-workflow-caller.yaml@dev
    with:
      username: Bala
    secrets:
      token: ${{ secrets.CICD_GIT_TOKEN }}

  call-workflow-B:
    uses: bakuppus/github-action-reusable-workflow/.github/workflows/reuseable-workflow-caller.yaml@dev
    with:
      username: Malathi
    secrets:
      token: ${{ secrets.CICD_GIT_TOKEN }}
